# Use official Python image
FROM python:3.14-slim

# Set work directory
WORKDIR /app/server

# Copy server code
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Start server
CMD ["uvicorn", "server:app", "--host", "127.0.0.1", "--port", "8000"]
